	/*
	BANCO DE DADOS UNIVERSIDADE

	* CADASTRA DADOS DA FACULDADE(MATERIAS, CURSOS, ALUNOS, PROFESSORES, MATRICULA)
	
	*DADOS DOS ALUNOS:
		IDMATRICULA(INT, CHAVE PRIMARIA AUTO INCREMENTO, NOT NULL),
		NOMEALUNO(VARCHAR, NOT NULL),
		SEXO(M/F, NOT NULL),

	*DADOS DOS PROFESSORES:
		IDPROFESSOR(INT, CHAVE PRIMARIA AUTO INCREMENTO, NOT NULL),
		NOMEPRO(VARCHAR, NOT NULL),

	*DADOS DOS CURSOS:
		SIGLACURSO(VARCHAR(3) CHAVE PRIMARIA, NOT NULL) EXEMPLO: SI(SISTEMAS DE INFORMACAO),
		NOMECUR(VARCHAR),
			
	*DADOS DAS MATERIAS:
		SIGLAMATERIA(VARCHAR(3), NOT NULL) EXEMPLO: BDA(BANCO DE DADOS),
		NOME(VARCHAR, NOT NULL),
		CARGAHORARIA(INT, NOT NULL),
		CURSO(VARCHAR(3), CHAVE ESTRANGEIRA(CURSO), NOT NULL),
		IDPROFESSOR(INT,),

	*DADOS DAS MATRICULAS:
		MATRICULA (INT),
        CURSO (CHAR(3)),
        MATERIA (CHAR(3)),
        PROFESSOR (INT),
        PERLETIVO (INT),

	*/
CREATE DATABASE UNIVILLE1
GO
USE UNIVILLE1
GO
CREATE TABLE ALUNOS
    (
	MATRICULA INT NOT NULL IDENTITY(1,1)
	CONSTRAINT PK_ALUNO PRIMARY KEY,
	NOMEALU VARCHAR(50) NOT NULL,
	SEXO VARCHAR(1) NOT NULL,
    );
GO
CREATE TABLE CURSOS
    (
	CURSO CHAR(3) NOT NULL
	CONSTRAINT PK_CURSO PRIMARY KEY,
	NOMECUR VARCHAR(50) NOT NULL
    );
GO
CREATE TABLE PROFESSORES
    (
	PROFESSOR INT IDENTITY NOT NULL
	CONSTRAINT PK_PROFESSOR PRIMARY KEY,
	NOMEPRO VARCHAR(50) NOT NULL
    );
GO
CREATE TABLE MATERIAS
    (
	SIGLA CHAR(3) NOT NULL,
	NOMEMAT VARCHAR(50) NOT NULL,
	CARGAHORARIA INT NOT NULL,
	CURSO CHAR(3) NOT NULL,
	PROFESSOR INT
	CONSTRAINT PK_MATERIA
	PRIMARY KEY (
                  SIGLA,
                  CURSO,
                  PROFESSOR
							)
	CONSTRAINT FK_CURSO
	FOREIGN KEY (CURSO) REFERENCES CURSOS (CURSO),
	CONSTRAINT FK_PROFESSOR
	FOREIGN KEY (PROFESSOR)
	REFERENCES PROFESSORES (PROFESSOR)
    );
GO
CREATE TABLE MATRICULA
    (
	MATRICULA INT IDENTITY NOT NULL,
	CURSO CHAR(3),
	MATERIA CHAR(3),
	PROFESSOR INT,
	PERLETIVO INT
	            CONSTRAINT PK_MATRICULA
            PRIMARY KEY (
                            MATRICULA,
                            CURSO,
                            MATERIA,
                            PROFESSOR,
                            PERLETIVO
                        ),
	CONSTRAINT FK_ALUNOS_MATRICULA
	FOREIGN KEY (MATRICULA)
	REFERENCES ALUNOS (MATRICULA),
	CONSTRAINT FK_CURSOS_MATRICULA
	FOREIGN KEY (CURSO)
	REFERENCES CURSOS (CURSO),
	CONSTRAINT FK_PROFESSOR_MATRICULA
	FOREIGN KEY (PROFESSOR)
	REFERENCES PROFESSORES (PROFESSOR)
);
GO
CREATE PROCEDURE procInputDados
(
@NOMEALU VARCHAR(50),
@SEXO VARCHAR(1),
@CURSO CHAR(3),
@NOMECUR VARCHAR(50),
@NOMEPRO VARCHAR(50),
@SIGLA CHAR(3),
@NOMEMAT VARCHAR(50),
@CARGAHORARIA INT,
@PROFESSOR VARCHAR(50)
)
AS
BEGIN
INSERT ALUNOS (NOMEALU, SEXO) VALUES (@NOMEALU, @SEXO)

INSERT CURSOS (CURSO, NOMECUR) VALUES (@CURSO, @NOMECUR)

INSERT PROFESSORES(NOMEPRO) VALUES (@NOMEPRO)

INSERT MATERIAS ( SIGLA, NOMEMAT, CARGAHORARIA, CURSO, PROFESSOR) VALUES (@SIGLA, @NOMEMAT, @CARGAHORARIA, @CURSO, @PROFESSOR)

END
GO
EXEC procInputDados		@NOMEALU = 'ROMEO',  --VARCHAR(50)
						@SEXO = 'M', --VARCHAR(50)
                        @CURSO = 'SDI', --CHAR(3)
						@NOMECUR =	'SISTEMAS', --VARCHAR(50)
						@NOMEPRO = 'GISLEA', --VARCHAR
						@SIGLA = 'CAL',	--CHAR(3)
						@NOMEMAT = 'CALCULO', --VARCHAR(50)
						@CARGAHORARIA = 150 ,	--INT
						@PROFESSOR = 2 --VARCHAR(50)



SELECT * FROM ALUNOS, CURSOS
left join MATRICULA on alunos.MATRICULA=MATRICULA.MATRICULA AND CURSOS.CURSO=MATRICULA.CURSO

